name: DanilBot

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */5 * * *'  # Перезапуск каждые 5 часов

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install groq pyTelegramBotAPI aiohttp Pillow openai
          
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GROQ_KEY: ${{ secrets.GROQ_KEY }}
        run: python danilbot

